General:
  Measurement: "CMS_ttbar"
  POI: "ttbar_norm"
  HistogramFolder: "histograms/"
  InputPath: "histograms_ml.root:{RegionPath}_{SamplePath}{VariationPath}"
  VariationPath: ""
  
Regions:

  - Name: "Feature0"
    RegionPath: "deltar_leptonbtoplep"
    Variable: "Delta R between $b_{top-lep}$ Jet and Lepton"
    Binning: [0.  , 0.24, 0.48, 0.72, 0.96, 1.2 , 1.44, 1.68, 1.92, 2.16, 2.4, 2.64, 2.88, 3.12, 3.36, 3.6 , 3.84, 4.08, 4.32, 4.56, 4.8 , 5.04, 5.28, 5.52, 5.76, 6.  ]
    
  - Name: "Feature1"
    RegionPath: "deltar_w1w2"
    Variable: "Delta R between the two W Jets"
    Binning: [0.  , 0.24, 0.48, 0.72, 0.96, 1.2 , 1.44, 1.68, 1.92, 2.16, 2.4, 2.64, 2.88, 3.12, 3.36, 3.6 , 3.84, 4.08, 4.32, 4.56, 4.8 , 5.04, 5.28, 5.52, 5.76, 6.  ]
    
  - Name: "Feature2"
    RegionPath: "deltar_w1btophad"
    Variable: "Delta R between first W Jet and $b_{top-had}$ Jet"
    Binning: [0.  , 0.24, 0.48, 0.72, 0.96, 1.2 , 1.44, 1.68, 1.92, 2.16, 2.4, 2.64, 2.88, 3.12, 3.36, 3.6 , 3.84, 4.08, 4.32, 4.56, 4.8 , 5.04, 5.28, 5.52, 5.76, 6.  ]
    
  - Name: "Feature3"
    RegionPath: "deltar_w2btophad"
    Variable: "Delta R between second W Jet and $b_{top-had}$ Jet"
    Binning: [0.  , 0.24, 0.48, 0.72, 0.96, 1.2 , 1.44, 1.68, 1.92, 2.16, 2.4, 2.64, 2.88, 3.12, 3.36, 3.6 , 3.84, 4.08, 4.32, 4.56, 4.8 , 5.04, 5.28, 5.52, 5.76, 6.  ]
    
  - Name: "Feature4"
    RegionPath: "mass_leptonbtoplep"
    Variable: "Combined Mass of $b_{top-lep}$ Jet and Lepton [GeV]"
    Binning: [ 50.,  60.,  70.,  80.,  90., 100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200., 210., 220., 230., 240., 250., 260., 270., 280., 290., 300.]
    
  - Name: "Feature5"
    RegionPath: "mass_w1w2"
    Variable: "Combined Mass of the two W Jets [GeV]"
    Binning: [ 50.,  60.,  70.,  80.,  90., 100., 110., 120., 130., 140., 150., 160., 170., 180., 190., 200., 210., 220., 230., 240., 250., 260., 270., 280., 290., 300.]
    
  - Name: "Feature6"
    RegionPath: "mass_w1w2btophad"
    Variable: "Combined Mass of $b_{top-had}$ Jet and the two W Jets [GeV]"
    Binning: [ 50.,  70.,  90., 110., 130., 150., 170., 190., 210., 230., 250., 270., 290., 310., 330., 350., 370., 390., 410., 430., 450., 470., 490., 510., 530., 550.]
    
  - Name: "Feature7"
    RegionPath: "pt_w1w2btophad"
    Variable: "Combined $p_T$ of $b_{top-had}$ Jet and the two W Jets [GeV]"
    Binning: [ 50.,  70.,  90., 110., 130., 150., 170., 190., 210., 230., 250., 270., 290., 310., 330., 350., 370., 390., 410., 430., 450., 470., 490., 510., 530., 550.]
    
  - Name: "Feature8"
    RegionPath: "pt_w1"
    Variable: "$p_T$ of the first W Jet [GeV]"
    Binning: [ 25.,  36.,  47.,  58.,  69.,  80.,  91., 102., 113., 124., 135., 146., 157., 168., 179., 190., 201., 212., 223., 234., 245., 256., 267., 278., 289., 300.]
    
  - Name: "Feature9"
    RegionPath: "pt_w2"
    Variable: "$p_T$ of the second W Jet [GeV]"
    Binning: [ 25.,  36.,  47.,  58.,  69.,  80.,  91., 102., 113., 124., 135., 146., 157., 168., 179., 190., 201., 212., 223., 234., 245., 256., 267., 278., 289., 300.]
    
  - Name: "Feature10"
    RegionPath: "pt_btophad"
    Variable: "$p_T$ of the $b_{top-had}$ Jet [GeV]"
    Binning: [ 25.,  36.,  47.,  58.,  69.,  80.,  91., 102., 113., 124., 135., 146., 157., 168., 179., 190., 201., 212., 223., 234., 245., 256., 267., 278., 289., 300.]
    
  - Name: "Feature11"
    RegionPath: "pt_btoplep"
    Variable: "$p_T$ of the $b_{top-lep}$ Jet [GeV]"
    Binning: [ 25.,  36.,  47.,  58.,  69.,  80.,  91., 102., 113., 124., 135., 146., 157., 168., 179., 190., 201., 212., 223., 234., 245., 256., 267., 278., 289., 300.]
    
  - Name: "Feature12"
    RegionPath: "btag_w1"
    Variable: "btagCSVV2 of the first W Jet [GeV]"
    Binning: [0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8, 0.84, 0.88, 0.92, 0.96, 1.  ]
    
  - Name: "Feature13"
    RegionPath: "btag_w2"
    Variable: "btagCSVV2 of the second W Jet [GeV]"
    Binning: [0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8, 0.84, 0.88, 0.92, 0.96, 1.  ]
    
  - Name: "Feature14"
    RegionPath: "btag_btophad"
    Variable: "btagCSVV2 of the $b_{top-had}$ Jet [GeV]"
    Binning: [0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8, 0.84, 0.88, 0.92, 0.96, 1.  ]
    
  - Name: "Feature15"
    RegionPath: "btag_btoplep"
    Variable: "btagCSVV2 of the $b_{top-lep}$ Jet [GeV]"
    Binning: [0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8, 0.84, 0.88, 0.92, 0.96, 1.  ]
    
  - Name: "Feature16"
    RegionPath: "qgl_w1"
    Variable: "qgl of the first W Jet [GeV]"
    Binning: [-1.  , -0.92, -0.84, -0.76, -0.68, -0.6 , -0.52, -0.44, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12,  0.2 ,  0.28,  0.36, 0.44,  0.52,  0.6 ,  0.68,  0.76,  0.84,  0.92,  1.  ]
    
  - Name: "Feature17"
    RegionPath: "qgl_w2"
    Variable: "qgl of the second W Jet [GeV]"
    Binning: [-1.  , -0.92, -0.84, -0.76, -0.68, -0.6 , -0.52, -0.44, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12,  0.2 ,  0.28,  0.36, 0.44,  0.52,  0.6 ,  0.68,  0.76,  0.84,  0.92,  1.  ]
    
  - Name: "Feature18"
    RegionPath: "qgl_btophad"
    Variable: "qgl of the $b_{top-had}$ Jet [GeV]"
    Binning: [-1.  , -0.92, -0.84, -0.76, -0.68, -0.6 , -0.52, -0.44, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12,  0.2 ,  0.28,  0.36, 0.44,  0.52,  0.6 ,  0.68,  0.76,  0.84,  0.92,  1.  ]
    
  - Name: "Feature19"
    RegionPath: "qgl_btoplep"
    Variable: "qgl of the $b_{top-lep}$ Jet [GeV]"
    Binning: [-1.  , -0.92, -0.84, -0.76, -0.68, -0.6 , -0.52, -0.44, -0.36, -0.28, -0.2 , -0.12, -0.04,  0.04,  0.12,  0.2 ,  0.28,  0.36, 0.44,  0.52,  0.6 ,  0.68,  0.76,  0.84,  0.92,  1.  ]
    

Samples:
  - Name: "Pseudodata"
    SamplePath: "pseudodata"
    Data: True

  - Name: "ttbar"
    SamplePath: "ttbar"

  - Name: "W+jets"
    SamplePath: "wjets"

  - Name: "single top, s-channel"
    SamplePath: "single_top_s_chan"

  - Name: "single top, t-channel"
    SamplePath: "single_top_s_chan"

  - Name: "tW"
    SamplePath: "single_top_tW"

Systematics:
  - Name: "ME variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_ME_var"
    Down:
      Symmetrize: True
    Samples: "ttbar"

  - Name: "PS variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_PS_var"
    Down:
      Symmetrize: True
    Samples: "ttbar"

  - Name: "ttbar scale variations"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_scaleup"
    Down:
      VariationPath: "_scaledown"
    Samples: "ttbar"

  - Name: "Jet energy scale"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_pt_scale_up"
    Down:
      Symmetrize: True

  - Name: "Jet energy resolution"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_pt_res_up"
    Down:
      Symmetrize: True

  - Name: "b-tag NP 1"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_0_up"
    Down:
      VariationPath: "_btag_var_0_down"

  - Name: "b-tag NP 2"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_1_up"
    Down:
      VariationPath: "_btag_var_1_down"

  - Name: "b-tag NP 3"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_2_up"
    Down:
      VariationPath: "_btag_var_2_down"

  - Name: "b-tag NP 4"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_3_up"
    Down:
      VariationPath: "_btag_var_3_down"

  - Name: "W+jets scale variations"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_scale_var_up"
    Down:
      VariationPath: "_scale_var_down"
    Samples: "W+jets"

  - Name: "Luminosity"
    Type: "Normalization"
    Up:
      Normalization: 0.03
    Down:
      Normalization: -0.03

NormFactors:
  - Name: "ttbar_norm"
    Samples: "ttbar"
    Nominal: 1.0
    Bounds: [0, 10]
