General:
  Measurement: "CMS_ttbar"
  POI: "ttbar_norm"
  HistogramFolder: "histograms/"
  InputPath: "histograms.root:{RegionPath}_{SamplePath}{VariationPath}"
  VariationPath: ""

Regions:
  - Name: "4j1b CR"
    RegionPath: "4j1b"
    Variable: "$H_T$ [GeV]"
    Binning: [110, 150, 190, 230, 270, 310, 350, 390, 430, 470, 510, 550]
  - Name: "4j2b SR"
    RegionPath: "4j2b"
    Variable: "$m_{bjj}$ [GeV]"
    Binning: [110, 150, 190, 230, 270, 310, 350, 390, 430, 470, 510, 550]

Samples:
  - Name: "Pseudodata"
    SamplePath: "pseudodata"
    Data: True

  - Name: "ttbar"
    SamplePath: "ttbar"

  - Name: "W+jets"
    SamplePath: "wjets"

  - Name: "single top, s-channel"
    SamplePath: "single_top_s_chan"

  - Name: "single top, t-channel"
    SamplePath: "single_top_t_chan"

  - Name: "tW"
    SamplePath: "single_top_tW"

Systematics:
  - Name: "ME variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_ME_var"
    Down:
      Symmetrize: True
    Samples: "ttbar"

  - Name: "PS variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_PS_var"
    Down:
      Symmetrize: True
    Samples: "ttbar"

  - Name: "ttbar scale variations"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_scaleup"
    Down:
      VariationPath: "_scaledown"
    Samples: "ttbar"

  - Name: "Jet energy scale"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_pt_scale_up"
    Down:
      Symmetrize: True

  - Name: "Jet energy resolution"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_pt_res_up"
    Down:
      Symmetrize: True

  - Name: "b-tag NP 1"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_0_up"
    Down:
      VariationPath: "_btag_var_0_down"

  - Name: "b-tag NP 2"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_1_up"
    Down:
      VariationPath: "_btag_var_1_down"

  - Name: "b-tag NP 3"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_2_up"
    Down:
      VariationPath: "_btag_var_2_down"

  - Name: "b-tag NP 4"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_btag_var_3_up"
    Down:
      VariationPath: "_btag_var_3_down"

  - Name: "W+jets scale variations"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_scale_var_up"
    Down:
      VariationPath: "_scale_var_down"
    Samples: "W+jets"

  - Name: "Luminosity"
    Type: "Normalization"
    Up:
      Normalization: 0.03
    Down:
      Normalization: -0.03

NormFactors:
  - Name: "ttbar_norm"
    Samples: "ttbar"
    Nominal: 1.0
    Bounds: [0, 10]
