FROM python:3.8-slim

ENV TZ=Etc/UTC

RUN pip install --no-cache-dir hist uproot matplotlib papermill ipykernel


WORKDIR /work
ENV HOME=/work

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copy all files from the Dockerfile directory to /work in the container
COPY . /work

RUN python -m ipykernel install --user

ENTRYPOINT ["/entrypoint.sh"]

# Start an interactive shell when the container is run
CMD ["/bin/bash"]
