rule all:
    input:  
        "histograms_merged.root"

# Create a rule for ttbar_nominal sample
rule ttbar_nominal_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_ttbar__nominal.root"
    params:
        key_to_extract = 'ttbar',
        variation = 'nominal'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample1_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule ttbar__scaledown_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_ttbar__scaledown.root"
    params:
         key_to_extract = 'ttbar',
         variation = 'scaledown'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample2_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule ttbar__scaleup_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_ttbar__scaleup.root"
    params:
        key_to_extract = 'ttbar',
        variation = 'scaleup'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample3_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule ttbar__ME_var_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_ttbar__ME_var.root"
    params:
        key_to_extract = 'ttbar',
        variation = 'ME_var'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample4_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule ttbar__PS_var_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_ttbar__PS_var.root"
    params:
        key_to_extract = 'ttbar',
        variation = 'PS_var'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample5_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule single_top_s_chan__nominal_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_single_top_s_chan__nominal.root"
    params:
        key_to_extract = 'single_top_s_chan',
        variation = 'nominal'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample6_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule single_top_t_chan__nominal_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_single_top_t_chan__nominal.root"
    params:
        key_to_extract = 'single_top_t_chan',
        variation = 'nominal'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample7_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule single_top_tW__nominal_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_single_top_tW__nominal.root"
    params:
        key_to_extract = 'single_top_tW',
        variation = 'nominal'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample8_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule wjets__nominal_sample:
    input:
        "samples.ipynb"
    output:
        "histograms_wjets__nominal.root"
    params:
        key_to_extract = 'wjets',
        variation = 'nominal'
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill {input} sample9_out.ipynb -p key_to_extract {params.key_to_extract} -p variation {params.variation} -k python3"

rule mergred_histograms:
    input:
        "merged.ipynb",
        "histograms_ttbar__nominal.root",
        "histograms_ttbar__ME_var.root",
        "histograms_ttbar__PS_var.root",
        "histograms_ttbar__scaleup.root",
        "histograms_ttbar__scaledown.root",
        "histograms_single_top_s_chan__nominal.root",
        "histograms_single_top_t_chan__nominal.root",
        "histograms_single_top_tW__nominal.root",
        "histograms_wjets__nominal.root"
    output:
        report("histograms_merged.root")
    params:
        merged_step = "Yes"
    container: 
        "povstenandrii/papermill:20231102a"
    shell:
        "/bin/bash -l && source fix-env.sh && papermill merged.ipynb sample_merged.ipynb -p merged_step {params.merged_step} -k python3"






