FROM docker.io/povstenandrii/papermill:20231102a

ENV TZ=Etc/UTC

RUN yum makecache && \
    yum -y install coreutils --allowerasing && \
    yum clean all

WORKDIR /work
ENV HOME=/work

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copy all files from the Dockerfile directory to /work in the container
COPY . /work

ENTRYPOINT ["/entrypoint.sh"]

# Start an interactive shell when the container is run
CMD ["/bin/bash"]