General:
  Measurement: "CabinetryHZZAnalysis"
  POI: "Signal_norm"
  HistogramFolder: "histograms/"
  InputPath: "histograms.root:{SamplePath}{VariationPath}"
  VariationPath: ""

Regions:
  - Name: Signal_region

Samples:
  - Name: "Data"
    SamplePath: "data"
    Data: True

  - Name: "Signal"
    SamplePath: "signal"

  - Name: "Background ZZ*"
    SamplePath: "ZZ"

  - Name: "Background Z, ttbar"
    SamplePath: "Z_tt"

Systematics:
  - Name: "Scalefactor_variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_SF_up"
    Down:
      VariationPath: "_SF_down"

  - Name: "m4l_variation"
    Type: "NormPlusShape"
    Up:
      VariationPath: "_m4l_up"
    Down:
      VariationPath: "_m4l_down"

  - Name: "ZZ_norm"
    Type: "Normalization"
    Up:
      Normalization: 0.1
    Down:
      Normalization: -0.1
    Samples: "Background ZZ*"

NormFactors:
  - Name: Signal_norm
    Samples: Signal
    Nominal: 1.0
    Bounds: [0, 10]
